// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjpcDkdW1e4C-tb4IfT4zN_kl2O_Y4kLQ',
    appId: '1:290830664216:web:dd2144a615eff70a8e796d',
    messagingSenderId: '290830664216',
    projectId: 'kisisel-harcama-kocu',
    authDomain: 'kisisel-harcama-kocu.firebaseapp.com',
    storageBucket: 'kisisel-harcama-kocu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsTk6frSHw84pDWK8LaW3FSnRUb7lxbPw',
    appId: '1:290830664216:android:ddb0f35fa43d81c48e796d',
    messagingSenderId: '290830664216',
    projectId: 'kisisel-harcama-kocu',
    storageBucket: 'kisisel-harcama-kocu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCbV72pbDwYjSnaJZuA4s0CRmxroxoiJI',
    appId: '1:290830664216:ios:e87f4dd1bbe9e0618e796d',
    messagingSenderId: '290830664216',
    projectId: 'kisisel-harcama-kocu',
    storageBucket: 'kisisel-harcama-kocu.firebasestorage.app',
    iosBundleId: 'com.example.kisiselHarcamaKocuSon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCbV72pbDwYjSnaJZuA4s0CRmxroxoiJI',
    appId: '1:290830664216:ios:e87f4dd1bbe9e0618e796d',
    messagingSenderId: '290830664216',
    projectId: 'kisisel-harcama-kocu',
    storageBucket: 'kisisel-harcama-kocu.firebasestorage.app',
    iosBundleId: 'com.example.kisiselHarcamaKocuSon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjpcDkdW1e4C-tb4IfT4zN_kl2O_Y4kLQ',
    appId: '1:290830664216:web:8b6f4f8ea9a147a28e796d',
    messagingSenderId: '290830664216',
    projectId: 'kisisel-harcama-kocu',
    authDomain: 'kisisel-harcama-kocu.firebaseapp.com',
    storageBucket: 'kisisel-harcama-kocu.firebasestorage.app',
  );
}
